### PR TITLE
Feature soillayerswap

### PR DESCRIPTION
**Pull request by dschlaep**
I moved #268 from the branch `Bugfix_247_STEPWAT_compatability` to a dedicated branch so that we can test the new functionality easier and apply it across SOILWAT2 development without waiting for the gridded STEPWAT2 to finalize.

### CODE REVIEW

**Comment by dschlaep** [comment]
My new unit test for the function `derive_soilRegions` fails to re-create its own inputs which are taken from files `testing/Input/siteparam.in` and `testing/Input/soils.in` with values 
```
# ndx               layer     # lower soil layer depth (cm)
	1		3            20.
	2		5            40.
	3		8           100.
```

See commit 54e71770e1850616869987d98b61a172f5bfae70:
```
test/test_SW_Site.cc:130: Failure
Expected equality of these values:
  prev_TranspRgnBounds[i]
    Which is: 2
  _TranspRgnBounds[i]
    Which is: 3
for transpiration region = 0 at a soil depth of 30 cm
test/test_SW_Site.cc:130: Failure
Expected equality of these values:
  prev_TranspRgnBounds[i]
    Which is: 4
  _TranspRgnBounds[i]
    Which is: 5
for transpiration region = 1 at a soil depth of 60 cm
```

@chaukap: any ideas?

**Comment by chaukap** [comment]
@dschlaep The fact that my function is consistently 1 value higher than the expected value leads me to believe that this is an indexing issue. Is `SW_Site->lyr` 0 indexed or 1 indexed? My assumption, which could very well be wrong, was that it is 1 indexed. This is why on line 746 of SW_Site.c is set `layer = 1;`. 

If `SW_Site->lyr` is 0 indexed all we need to do is change line 746 to `layer = 0;`.

Hopefully this was the problem. If not I'll dig deeper into the function and get is fixed.

Sorry about this!

**Comment by dschlaep** [comment]
@chaukap -- Great, thanks! Yes, `SW_Site.lyr` is base0-indexed. I'll fix it with my next commit.

**Comment by chaukap** [comment]
@dschlaep Perfect! I also reference `layer` as 1 indexed on line 751
```
while(totalDepth < regionLowerBounds[i] && layer <= v->n_layers &&
```
which should be 
```
while(totalDepth < regionLowerBounds[i] && layer < v->n_layers &&
```

**Comment by dschlaep** [comment]
@chaukap Thanks again! This is fixed and I added a few more unit tests. However, they are currently failing because I forgot about the `error: variable length arrays are a C99 feature [-Werror,-Wvla-extension]` on travis-ci.

**Comment by chaukap** [comment]
@dschlaep of course. Just let me know if there's anything else I can do.

**Comment by dschlaep** [comment]
@chaukap I merged this branch into https://github.com/DrylandEcology/SOILWAT2/pull/218 because we have unit tests more thoroughly set up there. I only needed to fix some issues with the documentation otherwise it works great. It would be great if you could review this branch before we merge it into SOILWAT2's master. It's ok that the code coverage checks are not met here because they will be on #218. Thanks!

**Comment by dschlaep** [comment]
@chaukap Great thanks! I merged this pull-request into master, and then updated https://github.com/DrylandEcology/SOILWAT2/pull/248 "Merge Bugfix_247 into master" from master (now v5.3.0)

**Pull request merged**
